export enum Errors {
  USER_BALANCE_ALREADY_EXISTS = 'USER_BALANCE_ALREADY_EXISTS',
  USER_BITCOIN_ADDRESS_ALREADY_EXISTS = 'USER_BITCOIN_ADDRESS_ALREADY_EXISTS',
  USER_BALANCE_INSUFFICIENT_AMOUNT = 'USER_BALANCE_INSUFFICIENT_AMOUNT',
  SHOP_BALANCE_INSUFFICIENT_AMOUNT = 'SHOP_BALANCE_INSUFFICIENT_AMOUNT',
}
